### ISSUE TITLE
Help please. ValueError: operands could not be broadcast together with remapped shapes

### ISSUE THREAD

**Issue by fan455** [lrenault/ddsp-piano#2]
Thanks for sharing your codes and models! I tried to run 'synthesize_midi_file.py' as you said, but encountered the below error:

(ddsp_test) F:\code\ddsp-piano-dev>python synthesize_midi_file.py "test01.mid" "test01.wav"
Loading midi file...
Traceback (most recent call last):
  File "synthesize_midi_file.py", line 63, in <module>
    main(process_args())
  File "synthesize_midi_file.py", line 32, in main
    inputs = load_midi_as_conditioning(args.midi_file, duration=args.duration)
  File "F:\code\ddsp-piano-dev\ddsp_piano\utils\io_utils.py", line 102, in load_midi_as_conditioning
    conditioning = ensure_sequence_length(conditioning, target_n_frames)
  File "F:\code\ddsp-piano-dev\ddsp_piano\utils\io_utils.py", line 61, in ensure_sequence_length
    return np.pad(sequence, pad_width=pad_width)
  File "<__array_function__ internals>", line 6, in pad
  File "F:\Envs\ddsp_test\lib\site-packages\numpy\lib\arraypad.py", line 743, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "F:\Envs\ddsp_test\lib\site-packages\numpy\lib\arraypad.py", line 518, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "F:\Envs\ddsp_test\lib\site-packages\numpy\lib\stride_tricks.py", line 411, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "F:\Envs\ddsp_test\lib\site-packages\numpy\lib\stride_tricks.py", line 350, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (6,)  and requested shape (3,2)

**Comment by lrenault** [comment]
Thanks for raising this bug in this very recent feature, it should be fixed by now in the latest commit in the dev branch (classic array vs list python confusion).
Code in the dev branch is still under heavy development and is not fully tested: stable code will be merged in the main branch.

**Comment by fan455** [comment]
Thanks for the fix! It now works very well. The synthesized result is very good!
